import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, ArrowRight, MessageSquare } from "lucide-react";
import styles from "../b2b-lead-generation-services/page.module.css";
import local from "./page.module.css";

const path = "/services/linkedin-marketing-services";
const title = "B2B LinkedIn Marketing Services for Technology Companies";
const description = "Build buyer trust with Stratskye's B2B LinkedIn marketing services: company and executive positioning, content, engagement, and demand-focused reporting.";
export const metadata: Metadata = { title: `${title} | Stratskye`, description, alternates: { canonical: path }, openGraph: { title, description, url: path, type: "website", images: [{ url: "/images/services/b2b-content-marketing/content-strategy-workshop.png", alt: "Team collaborating on a content strategy" }] } };
const gaps = [["No clear audience", "Content gets written for a general professional feed instead of a defined set of roles and industries, which means it reaches a lot of people who were never going to buy anything."], ["No credible voice", "A Company Page update carries less weight with a buyer than a founder or executive who clearly knows the subject firsthand, and most companies default to the weaker option."], ["No consistency", "A strong month followed by two months of silence tells both the algorithm and any buyer checking your profile that this is not an active priority, regardless of how good the earlier content was."], ["No connection to demand generation", "LinkedIn runs as its own island, disconnected from the rest of the marketing system, so even genuine engagement never turns into a tracked conversation."], ["No measurement beyond vanity metrics", "Impressions get reported because they are easy to pull, while the questions that actually matter, who is engaging and whether it leads anywhere, go unanswered."]];
const reasons = [["Technical fluency with complex products", "Our experience with B2B and technology companies means content briefs and SME interviews get built around what genuinely differentiates your product, rather than pulled from a generic industry template that could describe any competitor."], ["Strategy connected to execution", "Audience research, content, publishing, engagement, and reporting run through one team instead of getting handed off between departments that rarely talk to each other."], ["Executive voice, not just brand presence", "LinkedIn content built around a founder or executive's real expertise reads as credible to B2B buyers in a way company-only posting almost never does."], ["Connected to the wider demand system", "LinkedIn activity supports B2B demand generation rather than running in isolation, with downstream tracking of where it actually leads."], ["Structured delivery", "One main contact, weekly updates, and monthly reporting for the full engagement, so you always know what is happening and why."]];
const faqs = [["What do B2B LinkedIn marketing services include?", "Strategy, Company Page and executive profile optimization, content production, publishing and engagement, and performance reporting. Paid LinkedIn advertising and outbound automation live outside this scope and get handled as separate services."], ["Is this the same as LinkedIn Ads management?", "No. This service covers your organic LinkedIn presence and content. Paid campaigns fall under LinkedIn Ads Management Services, which can run alongside this engagement but gets scoped independently."], ["Do we need a founder or executive willing to be the voice on LinkedIn?", "Not necessarily one fixed person, but the content works best when it is built from real subject-matter expertise, whether that comes from a founder, an executive, or a subject-matter expert with regular availability."], ["How is this different from a general social media marketing agency?", "The work is built specifically around B2B technology buyers, longer sales cycles, and the specific credibility markers those buyers actually look for, rather than treating LinkedIn as a general brand awareness channel."], ["Will this generate leads directly?", "LinkedIn content can generate inbound interest and referral traffic, but this service does not include outbound prospecting or a guaranteed lead volume. It feeds demand generation rather than replacing it."], ["How much time will our team need to give this?", "Regular but limited access for SME interviews, brand and compliance guidance, and timely approvals. The heavier production work stays on our side."], ["Can Stratskye manage multiple executive profiles alongside the Company Page?", "Yes, and scope adjusts to match, since coordinating several voices takes more approvals and publishing planning than running one account."], ["How long before we see meaningful results?", "That depends on your starting audience, how consistent the content stays, and how connected your LinkedIn activity is to the rest of your demand system, so we will not promise a fixed timeline."], ["How does Stratskye measure whether LinkedIn is actually working?", "Through layered measurement covering visibility, engagement, audience quality, and demand, with pipeline visibility depending on your tracking and CRM data being accurate enough to support it."], ["What does Stratskye need from us to get started?", "Product and market context, access to your subject-matter experts, brand and compliance guidance, and timely feedback as the engagement runs."]];

const deliverables = [
  ["Audience & channel strategy", "An audit, defined buyer roles, content pillars, and a measurement plan that connect LinkedIn to your demand system."],
  ["Company & executive positioning", "Company Page and executive profile messaging that make your expertise and product relevance clear to buyers."],
  ["Expert-led content", "SME interviews, editorial planning, and content production built around your team's experience and point of view."],
  ["Publishing & engagement", "An agreed publishing cadence and engagement routines that keep the right conversations moving."],
  ["Performance & optimization", "Monthly reporting across visibility, audience quality, and demand signals, with recommendations for what to improve."],
  ["A coordinated engagement", "One main contact, weekly updates, and a clear approval process across your company and executive voices."],
];
const steps = [["Audit and align", "We review your current presence, define the audience, and set the content system and measurement plan together."], ["Build and publish", "Content gets produced, publishing activates, and engagement routines start running consistently."], ["Optimize", "We analyze what is actually resonating, adjust the approach based on real signals, and report on where to focus next."]];
const measurement = [["Visibility", "Impressions, reach, and profile or Company Page discovery."], ["Engagement", "Comments, shares, and conversations around your content."], ["Audience quality", "Whether the roles, companies, and industries engaging match your intended buyers."], ["Demand", "Inbound interest, referral traffic, and tracked conversations; pipeline visibility depends on tracking and CRM feedback."]];
const costs = [["Number of voices", "A single executive profile requires a different scope from a Company Page and several executive profiles."], ["Content volume & formats", "Publishing cadence, interviews, and production requirements shape the work involved."], ["Approval complexity", "Multiple stakeholders and compliance reviews affect coordination and publishing plans."], ["Measurement needs", "The state of your tracking and CRM determines the reporting work required."]];
const related = [["Parent service", "B2B Demand Generation Services", "/services/b2b-demand-generation-services"], ["Content and authority", "B2B Content Marketing Services", "/services/b2b-content-marketing-services"], ["Paid campaigns", "B2B Paid Media", "/services/b2b-paid-media-agency"], ["Prospecting and capture", "B2B Lead Generation Services", "/services/b2b-lead-generation-services"]];
function Intro({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) { return <div className={styles.sectionIntro}><p className={styles.eyebrow}>{eyebrow}</p><h2>{title}</h2>{copy && <p className={styles.sectionCopy}>{copy}</p>}</div>; }
function CallToAction() { return <Link className={styles.primaryButton} href="/contact-form">Book a Strategy Call <ArrowUpRight size={18} aria-hidden="true" /></Link>; }
export default function LinkedInMarketingPage() {
  const schema = { "@context": "https://schema.org", "@graph": [
    { "@type": "Service", name: title, description, url: `https://stratskye.com${path}`, provider: { "@type": "Organization", name: "Stratskye", url: "https://stratskye.com" }, isRelatedTo: { "@type": "Service", name: "B2B Demand Generation Services", url: "https://stratskye.com/services/b2b-demand-generation-services" } },
    { "@type": "BreadcrumbList", itemListElement: [["Services", "/services"], ["B2B Demand Generation", "/services/b2b-demand-generation-services"], ["LinkedIn Marketing", path]].map(([name, url], index) => ({ "@type": "ListItem", position: index + 1, name, item: `https://stratskye.com${url}` })) },
    { "@type": "FAQPage", mainEntity: faqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) },
  ] };
  return <main className={styles.page}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />
    <section className={styles.hero}><div className={styles.shell}>
      <nav className={local.breadcrumb} aria-label="Breadcrumb"><Link href="/services">Services</Link><span>/</span><Link href="/services/b2b-demand-generation-services">Demand Generation</Link><span>/</span><span aria-current="page">LinkedIn Marketing</span></nav>
      <div className={styles.heroGrid}><div><p className={styles.kicker}>Organic LinkedIn &middot; B2B technology</p><h1 className={local.title}>B2B LinkedIn Marketing Services <span>for Technology Companies</span></h1>
      <p className={styles.lede}>Having a LinkedIn presence and having one that actually brings in business are two very different things. Most B2B tech companies have the first.</p><p className={local.heroCopy}>Stratskye builds the second, turning scattered posting into a system where your company and your founder are the reason a buyer stops scrolling, remembers your name, and reaches out.</p><div className={styles.heroActions}><CallToAction /></div></div>
      <div className={styles.heroVisual}><Image src="/images/services/b2b-content-marketing/content-strategy-workshop.png" alt="Content team developing an editorial strategy together" fill sizes="(max-width: 900px) 100vw, 44vw" className={styles.coverImage} preload /><div className={styles.visualOverlay} /><div className={styles.pipelineCard}><div className={styles.pipelineTop}><span><MessageSquare size={20} aria-hidden="true" /> Your expertise, in the feed</span></div><div className={styles.pipelineFlow}><span>Expertise</span><ArrowRight size={15}/><span>Trust</span><ArrowRight size={15}/><span>Demand</span></div></div></div></div>
    </div></section>
    <section className={styles.lightSection}><div className={styles.shell}><Intro eyebrow="The role of LinkedIn" title="A presence built to earn buyer trust." copy="B2B LinkedIn marketing services manage a company&apos;s organic LinkedIn presence, including strategy, Company Page and executive profile positioning, content, engagement, and performance analytics, built to feed into demand generation rather than exist as its own disconnected task." /></div></section>
    <section className={styles.decisionSection}><div className={styles.shell}><div className={styles.decisionGrid}><div className={styles.stickyIntro}><p className={styles.eyebrow}>The missing connection</p><h2>Consistent posting is only the beginning.</h2><p>Here is the pattern that shows up in almost every audit we run. A company posts consistently for a few weeks, sees modest engagement, and the momentum fades before anyone on the buying side has actually noticed. The problem usually is not effort. It is that the effort was never pointed at the specific things that make LinkedIn work for B2B.</p></div><div className={styles.decisionList}>{gaps.map(([heading, text], i) => <div className={local.gap} key={heading}><span>0{i + 1}</span><div><h3>{heading}</h3><p>{text}</p></div></div>)}</div></div></div></section>
    <section className={styles.servicesSection}><div className={styles.shell}><Intro eyebrow="What we deliver" title="One connected LinkedIn content system." copy="Each deliverable below exists because it solves one of the gaps above. None of them work particularly well on their own." /><div className={styles.serviceGrid}>{deliverables.map(([heading, text], i) => <article className={`${styles.serviceCard} ${local.deliverable}`} key={heading}><div className={styles.serviceCardTop}><span>0{i + 1}</span><MessageSquare size={22} aria-hidden="true" /></div><h3>{heading}</h3><p>{text}</p></article>)}</div><p className={local.note}>This engagement covers organic LinkedIn. Paid LinkedIn advertising and outbound automation are scoped separately.</p></div></section>
    <section className={styles.whySection}><div className={styles.shell}><Intro eyebrow="Why Stratskye" title="Technical depth. A credible human voice." /><div className={styles.reasonList}>{reasons.map(([heading, text], i) => <div className={styles.reasonItem} key={heading}><span>0{i + 1}</span><div><h3>{heading}</h3><p>{text}</p></div></div>)}</div><Link className={local.textLink} href="/services/b2b-demand-generation-services">Explore the wider demand generation system <ArrowUpRight size={18}/></Link></div></section>
    <section className={styles.processSection}><div className={styles.shell}><Intro eyebrow="How it works" title="Strategy before the first post." /><p className={local.note}>Strategy comes before a single piece of content gets written. Content built without a defined audience and a clear voice tends to read as generic no matter how well it is produced.</p><div className={styles.processGrid}>{steps.map(([heading, text], i) => <article className={styles.processCard} key={heading}><span>0{i + 1}</span><div><h3>{heading}</h3><p>{text}</p></div></article>)}</div><p className={local.note}>We need product and market context, access to your subject-matter experts, brand and compliance guidance, and timely approvals from your side throughout.</p></div></section>
    <section className={styles.measureSection}><div className={styles.shell}><Intro eyebrow="Measurement" title="Look beyond the impression count." copy="Visibility numbers tell you whether content is getting seen. Audience quality tells you whether it is being seen by the right people. Neither one, on its own, tells you whether any of it is actually contributing to pipeline. That last question depends on tracking and CRM feedback working together properly." /><p className={styles.sectionCopy}>We report across these layers together, so you can see whether content is reaching the roles that actually matter to your business, not just generating reach for its own sake.</p><div className={styles.tableWrap}>{measurement.map(([heading, text]) => <div className={styles.tableRow} key={heading}><strong>{heading}</strong><span>{text}</span></div>)}</div>
      <div className={local.analytics}><figure><Image src="/images/M1 Performance/linkedin content impression.PNG" alt="M1 Performance LinkedIn analytics recording 7,120,391 content impressions" width={680} height={599} sizes="(max-width: 700px) 100vw, 45vw" /><figcaption>M1 Performance &middot; LinkedIn content impressions</figcaption></figure><figure><Image src="/images/M1 Performance/linkedin engagement.PNG" alt="M1 Performance LinkedIn analytics recording 75,735 social engagements" width={696} height={598} sizes="(max-width: 700px) 100vw, 45vw" /><figcaption>M1 Performance &middot; LinkedIn engagement</figcaption></figure></div><p className={styles.sectionCopy}>These analytics show visibility and engagement from a broader client engagement; they are not a forecast or a pipeline attribution claim.</p><Link className={local.textLink} href="/case-study/m1-performance">Read the M1 Performance case study <ArrowUpRight size={18}/></Link>
    </div></section>
    <section className={styles.costSection}><div className={styles.shell}><Intro eyebrow="Engagement scope" title="Built around the voices you need." /><p className={local.note}>Every engagement gets scoped after diagnosis, because the work involved in running a single executive voice looks nothing like the work involved in running a Company Page alongside three executive profiles at once.</p><div className={styles.costGrid}>{costs.map(([heading, text], i) => <div className={styles.costItem} key={heading}><span>0{i + 1}</span><div><strong>{heading}</strong><p>{text}</p></div></div>)}</div></div></section>
    <section className={styles.relatedSection}><div className={styles.shell}><Intro eyebrow="Related services" title="Part of a wider demand system." copy="LinkedIn marketing rarely earns its keep as an isolated channel. It connects most naturally to a broader demand system and to a few adjacent services, depending on what else your company needs." /><div className={styles.relatedGrid}>{related.map(([need, label, href]) => <Link className={styles.relatedLink} href={href} key={href}><span>{need}</span><strong>{label}</strong><ArrowUpRight size={18}/></Link>)}</div></div></section>
    <section className={styles.faqSection}><div className={styles.shell}><Intro eyebrow="FAQ" title="Your LinkedIn marketing questions, answered." /><div className={styles.faqList}>{faqs.map(([question, answer], i) => <details className={styles.faqItem} key={question} open={i === 0}><summary><span>{question}</span><span className={styles.faqPlus} aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div><div className={local.faqAction}><CallToAction /></div></div></section>
    <section className={styles.finalCta}><div className={styles.finalGlow} aria-hidden="true"/><div className={styles.shell}><div className={styles.ctaInner}><p className={styles.eyebrow}>Make your expertise visible</p><h2>Be the name your buyers remember.</h2><p>If your LinkedIn activity is not translating into buyer trust or pipeline visibility, that is exactly the gap this service closes.</p><CallToAction /><span className={styles.proofLine}>Stratskye has worked with B2B technology companies across SaaS, fintech, and infrastructure since 2019.</span></div></div></section>
  </main>;
}
